version: "3.8"

services:
  mc-fabric:
    image: itzg/minecraft-server:latest
    container_name: proximity-optimized-vanilla
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.6"
      PACKWIZ_URL: "https://raw.githubusercontent.com/admlars2/proximity-optimized-vanilla/main/pack.toml"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MEMORY: "6G"
      
      ENABLE_WHITELIST: "TRUE"
      WHITELIST: "YourUsername"
    
    volumes:
      - ./data:/data              # persistant data
    
    ports:
      - "25565:25565/tcp"         # Minecraft
      - "24454:24454/udp"         # Simple VC
    
    restart: unless-stopped
