name = "Proximity Optimized Vanilla"
author = "Cosmo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d335710b3b66cdf10f2ee1c8bc8cdab09958f8fccec4ff0173463c0bbfeef51f"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
