name = "Proximity Optimized Vanilla"
author = "Cosmo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cec185a05ec1c2a690d2bea6dd1454eda4555bf5f94f2ce29545dca51718af42"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
