name = "Proximity Optimized Vanilla"
author = "Cosmo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe29c5cacdb728c1b7495f1a66729e1790405dfa77f4b5d5e801667d13bfdea6"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
