name = "Proximity Optimized Vanilla"
author = "Cosmo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d45092621b435de019b5d58e3a98c1a7cc4f7afb3e14305f51c76dd5e4212c0"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
